[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.3"
tokio = { version = "1.41.1", features = ["full"] }
tonic = { version = "0.12.3", features = ["gzip"] }

[build-dependencies]
prost-build = "0.13.3"
tonic-build = "0.12.3"
